name: flutter_firebase_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  provider: ^6.0.5
  equatable: ^2.0.5
  either_dart: ^0.3.0
  dev: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  fake_cloud_firestore: ^2.0.0


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true